# Generated by Django 4.1.3 on 2022-11-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slot',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
